version: '2'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      # image: nimbustech/postgres-ssl:9.5
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  local.keycloak.com:
      build: 
        context: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. 
        # The parameter below is just an example, and it shouldn't be used in production without knowledge. 
        # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        JDBC_PARAMS: "ssl=yes"
      ports:
        - 8080:8080
        - 8443:8443
      depends_on:
        - postgres
  # manageiq:
  server:
      privileged: true
      build: 
        context: manageiq
      ports:
        - 443:443
      depends_on:
        - local.keycloak.com