#!/bin/bash

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/rh-postgresql95/root/usr/lib64/
PG_DUMP=/opt/rh/rh-postgresql95/root/usr
export PG_DUMP
PATH=$PG_DUMP/bin:$PATH
export PATH

/usr/sbin/crond &

check-dependent-services.sh
appliance-initialize.sh

[[ -s /etc/default/evm ]] && source /etc/default/evm

exec ruby /var/www/miq/vmdb/lib/workers/bin/evm_server.rb